[server]
headless = true
port = $PORT
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[python]
# Adjusting the paths to ensure modules can be found
pythonPath = "src"
